mongodb:
  image: mongo:3.0.1
  command: mongod --smallfiles --quiet --logpath=/dev/null
  ports:
    - 27017:27017

graphite:
  image: sitespeedio/graphite
  ports:
    - 8081:80
    - 2003:2003  

collectd:
  image: listhub/collectd-write-graphite
  links:
    - graphite
  environment:
    HOST_NAME: sample
    GRAPHITE_HOST: graphite
    GRAPHITE_PORT: 2003
    INSTANCE_ID: seyren
